### ISSUE TITLE
Redirects logs intended for console to file

### ISSUE THREAD

**Issue by JustWalters** [juttle/winston-logrotate#4]
This transport overwrites stdout and stderr so when the console transport tries to log something, the data gets sent to the file instead. Removing these lines fixes the issue and I haven't noticed it causing any new problems, but maybe I'm missing something.

**Comment by lukebarnard1** [comment]
@JustWalters which lines ooi?

**Comment by iongion** [comment]
Can this fix be applied ?

**Comment by demmer** [comment]
Fixed
