### ISSUE TITLE
Formatter is not applied

### ISSUE THREAD

**Issue by kursattokpinar** [juttle/winston-logrotate#8]
Hi,
It seems logrotate does not use formatter. 
`var output = common.log({
        colorize: this.colorize,
        json: this.json,
        level: level,
        message: msg,
        meta: meta,
        stringify: this.stringify,
        timestamp: this.timestamp,
        prettyPrint: this.prettyPrint
    });`

I have added a line `formatter: this.formatter` and issue seems vanished. Could you please evaluate this solution?

**Comment by jathanasiou** [comment]
I have added a [pull request](https://github.com/juttle/winston-logrotate/pull/9) to fix this issue as well, please merge if possible.
